# Generated by Django 4.2.4 on 2023-11-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('fees', models.IntegerField(max_length=200)),
                ('duraction', models.CharField(max_length=200)),
            ],
        ),
    ]
